/**
 * Store actions types
 */
export const ACTIONS_TYPES = {
  FORM_SIGNUP_UPDATE: 'FORM_SIGNUP_UPDATE',
  FORM_SIGNUP_INITIALIZE: 'FORM_SIGNUP_INITIALIZE',
  FORM_SIGNUP_RESULT: 'FORM_SIGNUP_RESULT',
  FORM_SIGNUP_PENDING: 'FORM_SIGNUP_PENDING',
  MODAL_CHANGE: 'MODAL_CHANGE'
}
